export const DUMMY_TODOS = [
  {
    id: '1',
    userId: '101',
    title: 'Buy groceries',
    desc: 'Milk, Eggs, Bread, and Butter',
    dueDate: '2024-09-30',
    isCompleted: false,
  },
  {
    id: '2',
    userId: '102',
    title: 'Complete project report',
    desc: 'Finish the final draft of the project report',
    dueDate: '2024-09-25',
    isCompleted: false,
  },
  {
    id: '3',
    userId: '103',
    title: 'Plan weekend trip',
    desc: 'Research and book a hotel for the trip',
    dueDate: '2024-09-28',
    isCompleted: true,
  },
  {
    id: '4',
    userId: '101',
    title: 'Workout session',
    desc: 'Attend yoga class in the evening',
    dueDate: '2024-09-24',
    isCompleted: false,
  },
  {
    id: '5',
    userId: '104',
    title: 'Call mom',
    desc: 'Check in with mom and plan dinner',
    dueDate: '2024-09-22',
    isCompleted: true,
  },
  {
    id: '6',
    userId: '105',
    title: 'Prepare presentation',
    desc: 'Prepare slides for the team meeting',
    dueDate: '2024-09-26',
    isCompleted: false,
  },
  {
    id: '7',
    userId: '106',
    title: 'Dentist appointment',
    desc: 'Routine check-up at 3 PM',
    dueDate: '2024-09-27',
    isCompleted: false,
  },
  {
    id: '8',
    userId: '102',
    title: 'Read new book',
    desc: "Start reading 'Atomic Habits'",
    dueDate: '2024-09-29',
    isCompleted: true,
  },
  {
    id: '9',
    userId: '103',
    title: 'Fix bike tire',
    desc: 'Replace the rear tire of the bike',
    dueDate: '2024-09-23',
    isCompleted: false,
  },
  {
    id: '10',
    userId: '104',
    title: 'Attend coding workshop',
    desc: 'React & Next.js online workshop',
    dueDate: '2024-09-25',
    isCompleted: false,
  },
];
